services:
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: maven_central
    volumes:
      - db_data:/var/lib/mysql
      - ./mariadb:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"
    healthcheck:
      interval: 30s
      retries: 3
      test:
        [
          "CMD",
          "healthcheck.sh",
          "--su-mysql",
          "--connect",
          "--innodb_initialized"
        ]
      timeout: 30s

volumes:
  db_data:
